#!/bin/bash
#
# Easy dd #
#
# Choose the right drive:
# -----------------------
# Run the "lsblk" command and choose the destination drive,
# i.e. /dev/sdb1
#
# How to use the script:
# ---------------------
# Use two arguments to run the script:
# edd /path/to/source/file /path/to/destination
#
# Be carful!:
# ----------
# Use the script with caution, it will delete everything on the destination
# drive.
#

SRC=$1
DST=$2

if [ $# -ne 2 ]; then
    echo -e "\e[31mWrong number of arguments\e[0m"
    echo "Usage:"
    echo "edd [source] [destination]"
    echo
    exit 1

else
    echo "Source file size: $(du -hs $SRC)"

    echo -e "\e[31mBurning image to disk...\e[0m"

    dd if=$SRC of=$DST status=progress && echo -e "\e[32mDone!\e[0m"

fi
